{
  "services": [
    {
      "type": "web",
      "name": "fincontrol",
      "env": "node",
      "plan": "free",
      "buildCommand": "npm install && npm run build",
      "startCommand": "npm start",
      "envVars": [
        {
          "key": "NEXT_PUBLIC_SUPABASE_URL",
          "sync": false
        },
        {
          "key": "NEXT_PUBLIC_SUPABASE_ANON_KEY",
          "sync": false
        },
        {
          "key": "SUPABASE_SERVICE_ROLE_KEY",
          "sync": false
        },
        {
          "key": "NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL",
          "value": ""
        }
      ]
    }
  ]
}
